In [1]:
import requests
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
# Get sample data
url = 'https://agmarknet.gov.in/SearchCmmMkt.aspx?Tx_Commodity=24&Tx_State=UP&Tx_District=1&Tx_Market=0&DateFrom=20-Mar-2021&DateTo=20-Mar-2021&Fr_Date=20-Mar2021&To_Date=20-Mar2021&Tx_Trend=0&Tx_CommodityHead=Potato&Tx_StateHead=Uttar+Pradesh&Tx_DistrictHead=Agra&Tx_MarketHead=--Select--'
html = requests.get(url).content
df_list = pd.read_html(html)
df = df_list[-1]

In [3]:
columns_list = list(df.columns)
# start => month-date-year
date_range = pd.date_range(start='1-1-2020', end='12-31-2020', freq='1D')

# Extract Dates in 2 formats like '20-Mar-2021' and '20-Mar2021'
date1_format = []
for i in date_range:
    date1_format.append(i.strftime('%d-%b-%Y'))

date2_format = []
for i in date_range:
    date2_format.append(i.strftime('%d-%b%Y'))
# print(date2_format)

In [4]:

# Total DataFrame
total_data = pd.DataFrame(columns=columns_list)


for date1, date2 in tqdm(zip(date1_format, date2_format)):
    url = 'https://agmarknet.gov.in/SearchCmmMkt.aspx?Tx_Commodity=24&Tx_State=UP&Tx_District=1&Tx_Market=0&DateFrom='+date1+'&DateTo='+date1 + \
        '&Fr_Date='+date2+'&To_Date='+date2 + \
        '&Tx_Trend=0&Tx_CommodityHead=Potato&Tx_StateHead=Uttar+Pradesh&Tx_DistrictHead=Agra&Tx_MarketHead=--Select--'
    html = requests.get(url).content
    df_list = pd.read_html(html)
    df = df_list[-1]
    if 'Min Price (Rs./Quintal)' not in list(df.columns):
        df['Min Price (Rs./Quintal)'] = df[['Min Price (Rs/Quintal)']]
        df['Max Price (Rs./Quintal)'] = df[['Max Price (Rs/Quintal)']]
        df['Modal Price (Rs./Quintal)'] = df[['Modal Price (Rs/Quintal)']]
    total_data = pd.concat([total_data, df[columns_list]],ignore_index=True, sort=False)
    
# df = df_list[-1]
# #print(df_list)

print(total_data.head)
total_data.to_csv("total_data.csv")

366it [10:25,  1.71s/it]

<bound method NDFrame.head of      Sl no. District Name     Market Name Commodity Variety Grade  \
0         1          Agra         Achnera    Potato    Desi   FAQ
1         2          Agra  Fatehpur Sikri    Potato   Local   FAQ
2         3          Agra         Jagnair    Potato    Desi   FAQ
3         4          Agra           Jarar    Potato    Desi   FAQ
4         5          Agra      Khairagarh    Potato    Desi   FAQ
...     ...           ...             ...       ...     ...   ...
1823      1          Agra            Agra    Potato    Desi   FAQ
1824      2          Agra       Fatehabad    Potato    Desi   FAQ
1825      3          Agra  Fatehpur Sikri    Potato   Local   FAQ
1826      4          Agra         Jagnair    Potato    Desi   FAQ
1827      5          Agra      Khairagarh    Potato    Desi   FAQ

     Min Price (Rs./Quintal) Max Price (Rs./Quintal)  \
0                       1300                    1400
1                       1400                    1520
2                       1250                    1350
3                       1200                    1300
4                       1200                    1300
...                      ...                     ...
1823                     800                    1100
1824                     700                     800
1825                     900                    1100
1826                     750                     850
1827                    1100                    1200

     Modal Price (Rs./Quintal)   Price Date
0                         1350  01 Jan 2020
1                         1455  01 Jan 2020
2                         1300  01 Jan 2020
3                         1250  01 Jan 2020
4                         1250  01 Jan 2020
...                        ...          ...
1823                       960  31 Dec 2020
1824                       750  31 Dec 2020
1825                      1015  31 Dec 2020
1826                       800  31 Dec 2020
1827                      1150  31 Dec 2020

[1828 rows x 10 columns]>

In [5]:
total_data.head(10)

,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date
0,1,Agra,Achnera,Potato,Desi,FAQ,1300,1400,1350,01 Jan 2020
1,2,Agra,Fatehpur Sikri,Potato,Local,FAQ,1400,1520,1455,01 Jan 2020
2,3,Agra,Jagnair,Potato,Desi,FAQ,1250,1350,1300,01 Jan 2020
3,4,Agra,Jarar,Potato,Desi,FAQ,1200,1300,1250,01 Jan 2020
4,5,Agra,Khairagarh,Potato,Desi,FAQ,1200,1300,1250,01 Jan 2020
5,6,Agra,Samsabad,Potato,Local,FAQ,1100,1300,1200,01 Jan 2020
6,1,Agra,Agra,Potato,Desi,FAQ,1300,1500,1400,02 Jan 2020
7,2,Agra,Fatehabad,Potato,Desi,FAQ,1180,1250,1200,02 Jan 2020
8,3,Agra,Fatehpur Sikri,Potato,Local,FAQ,1360,1500,1420,02 Jan 2020
9,4,Agra,Jagnair,Potato,Desi,FAQ,1200,1400,1300,02 Jan 2020